name: Addicted Bespoke
favicon: null
layout_spectrum: 0.03547953208908439
typography_spectrum: 0.48524
title: Your Private Tailor So Amazing You'll Become Addicted
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e3deda'
    - '#363755'
    - '#9f6d54'
    - '#ca9667'
    - '#567241'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
